### ISSUE TITLE
angular error on filtering  and paging

### ISSUE THREAD

**Issue by gerald-datz** [OPSI-srl/UManage#3] opened 2016-07-12 11:02 UTC
Hi

First: Great tool-thanks for sharing this with the community, I really like it a lot!

I have an DNN 07.04.02 (216) Installation with UMANAGE 0.2.4. with three issues I found:

**#1: Role filter and paging:**
I am facing issues by trying to change to another page of users if there is a role-filter active that has more results than fitting on a single page
The top-info besides the paging control shows the correct number of results and pages and i can use the arrows to flip through the pages. But the results (cards or list) do not change - Just always shows the first page of results 

in the javascript console i get the following error:
angular.min.js?cdv=111:103 TypeError: filters.roles.join is not a function
    at $OpsiUserTiles.$self.loadUsers (controller.js?cdv=111:394)
    at controller.js?cdv=111:436
    at l.$broadcast (angular.min.js?cdv=111:129)
    at l.$scope.changePage (controller.js?cdv=111:344)
    at angular.min.js?cdv=111:198
    at l.$eval (angular.min.js?cdv=111:126)
    at angular.min.js?cdv=111:213
    at angular.min.js?cdv=111:226
    at s (angular.min.js?cdv=111:7)
    at $$writeModelToScope (angular.min.js?cdv=111:226)

This does not happen when I do not have a role selected as a filter 

**#2: Paging Controls behaviour and size**
The arrows in the paging box are really very small - especially on a 4k display they become really unuseable - also sometimes if you leave the mousepointer over the buttons after you clicked once the pages run through till the end(last page) 

**#3: Only useable with admin rights?**
If I give access to users with no Portal Admin rights (user has no Role "Administrators") then the module seems to work, but only shows "Fast Edit" in the list or on the card-Function Buttons.
The "Full DNN Edit" and "Impersonate" functions are no more there...

Hope you can help me out with this issues
Any help is highly appreciated
Thanks in advance and kind regards
Gerald

**Comment by OctoD** [comment] 2016-07-12 12:17
Hello Gerald, thanks for you report!

Concerning the first issue (#1) we're investingating right now and we are going to commit a fix as soon as possible (will be released as a patch, 0.2.5).

About the second (#2) we will release a better ui component (not the standard input[type=number] html5) for the pagination in the next minor release, we beg your pardon if it will not be immediate.

Concerning the third, it was designed this way because of technical difficulties (would require a lot of time to let non-admin/host users to impersonate or full edit a user profile), so we could not guarantee a fix at this time.

Thanks for using, UManage!

**Comment by gerald-datz** [comment] 2016-08-01 08:22
Hi OctoD
Sorry for beeing impatient, but is there any progress on the paging error?
thanks in advance for your help
regards
Gerald

**Comment by OctoD** [comment] 2016-08-01 10:59
Hello Gerald, I'm so sorry for the time we're taking to close these issues. I've just committed a fix which should close the issue with point #1 . Just let me now if it works as expected.

Thanks

**Comment by OctoD** [comment] 2016-08-02 07:29
@gerald-datz you should download this hotfix and unpack inside your ~/DesktopModules/UManage folder. Backup your  ~/DesktopModules/UManage/app folder first, since it was barely tested. (But I assume it should work)
[hotfix1.zip](https://github.com/OPSI-srl/UManage/files/395458/hotfix1.zip)

**Closed as completed** 2016-08-03 13:49 UTC
Labels: bug, enhancement, question
